[toolchain]
channel = "nightly-2025-09-09"

components = [
    "rust-src",
    "rustc-dev",
    "rustfmt",
    "llvm-tools-preview",
    "rustfmt",
    "rust-docs",

    # "clippy",
    # "llvm-bitcode-linker",
    # "rust-std-wasm32-unknown-emscripten",
    # "rust-std-wasm32-unknown-unknown",
    # "rust-analysis",
    # "rust-analyzer",
    # "rustc-codegen-cranelift",
    # "rust-docs-json",
]

targets = [
    "aarch64-apple-darwin",
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu",

    # "wasm32-unknown-emscripten",
    # "wasm32-unknown-unknown",
    # "wasm32-wasip1",
    # "wasm32-wasip1-threads",
    # "wasm32-wasip2",
    # "wasm32v1-none",
]